# 端口
server:
  port: 8090

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  application:
    name: springbootDemo



#打印SQL日志
logging:
  level:
    com:
      bngrp:
        mapper: debug

